[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "pageros"
version = "0.0.1"
description = "Python SDK for PagerOS"
requires-python = ">=3.10"
readme = "README.md"
license = { text = "MIT" }
authors = [{ name = "PagerOS Team" }]

[tool.setuptools.packages.find]
include = ["pageros*"]

[project.scripts]
pageros-dev = "pageros.devserver:main"
