idf_component_register(
    SRCS "main.c"
    INCLUDE_DIRS "."
    REQUIRES
        selftest
        gps
        input
        keyboard
        input_router
        identity
        logger
        lora
        storage
        network
        display
        imu
        apprt
        shell
        widgets
        fonts
        sideload
        cbor_codec
        i2c_bus
        xl9555
        power
        audio
        nfc
        nvs_flash
        app_update
        esp_hw_support
        esp_timer
        spi_flash
        log
)
